In [3]:
import numpy as np
from math import sin, cos, radians

In [8]:
import numpy as np
from math import sin, cos, radians

def rotate(coords:np.array, axis:str, angle:int) -> np.array:
    """
    Use standard rotation matrices to rotate three-dimensional coordinates 
    around an axis by specified angle
    """
    angle=radians(angle)
    if axis == 'x':
        rot = np.array([
            [1, 0, 0],
            [0, round(cos(angle),0), -round(sin(angle),0)],
            [0, round(sin(angle),0), round(cos(angle),0)]
        ])
    elif axis == 'y':
        rot = np.array([
            [round(cos(angle),0), 0, round(sin(angle),0)],
            [0, 1, 0],
            [-round(sin(angle),0), 0, round(cos(angle),0)]
        ])
    elif axis == 'z':
        rot = np.array([
            [round(cos(angle),0), -round(sin(angle),0),0],
            [round(sin(angle),0), round(cos(angle),0),0],
            [0, 0, 1]
        ])
    else:
        raise ValueError('Axis should be one of: "x", "y", "z"')
    
    # Matrix multiplaction
    return np.matmul(rot, coords).astype('int')

In [30]:
def all_orients(coords:list) -> list:
    """
    Take a input list of xyz coordinates (represented as (1,3) np.arrays)
    and rotate these into each of 24 possible orientations assuming 90 degree rotations along axes.
    """
    all_rotated = []
    for coord in coords:
        one_rotated = []
        # Each angle along x & y axes. Double rotate (includes 0 degree so also single rotations)
        for x_angle in (0, 90,180,270):
            for y_angle in (0, 90,180,270):
                one_rotated.append(rotate(rotate(coord, 'x', x_angle), 'y', y_angle))
            # For z axis only look at two rotations as others covered by origin position and x & y double rotations
            for z_angle in (90, 270):
                one_rotated.append(rotate(rotate(coord, 'x', x_angle), 'z', z_angle))
        all_rotated.append(one_rotated)
    return all_rotated
            

In [31]:
test = np.array([5,10,15])
test.shape
# rotate(test, 'y', 90)

(3,)

In [36]:
all_orients(a)

[[array([ 404, -588, -901]),
  array([-901, -588, -404]),
  array([-404, -588,  901]),
  array([ 901, -588,  404]),
  array([ 588,  404, -901]),
  array([-588, -404, -901]),
  array([ 404,  901, -588]),
  array([-588,  901, -404]),
  array([-404,  901,  588]),
  array([588, 901, 404]),
  array([-901,  404, -588]),
  array([ 901, -404, -588]),
  array([404, 588, 901]),
  array([ 901,  588, -404]),
  array([-404,  588, -901]),
  array([-901,  588,  404]),
  array([-588,  404,  901]),
  array([ 588, -404,  901]),
  array([ 404, -901,  588]),
  array([ 588, -901, -404]),
  array([-404, -901, -588]),
  array([-588, -901,  404]),
  array([901, 404, 588]),
  array([-901, -404,  588])],
 [array([ 528, -643,  409]),
  array([ 409, -643, -528]),
  array([-528, -643, -409]),
  array([-409, -643,  528]),
  array([643, 528, 409]),
  array([-643, -528,  409]),
  array([ 528, -409, -643]),
  array([-643, -409, -528]),
  array([-528, -409,  643]),
  array([ 643, -409,  528]),
  array([ 409,  528, -643

In [12]:
# Euclidean distance

a = np.array([0,10,20])
b = np.array([0,10,-20])

np.linalg.norm(a-b)

40.0

In [13]:
# Sample data - make sure you can determine 12+ of coordinates are consistent distance between a & b

a = [
    np.array([404,-588,-901]),
    np.array([528,-643,409]),
    np.array([-838,591,734]),
    np.array([390,-675,-793]),
    np.array([-537,-823,-458]),
    np.array([-485,-357,347]),
    np.array([-345,-311,381]),
    np.array([-661,-816,-575]),
    np.array([-876,649,763]),
    np.array([-618,-824,-621]),
    np.array([553,345,-567]),
    np.array([474,580,667]),
    np.array([-447,-329,318]),
    np.array([-584,868,-557]),
    np.array([544,-627,-890]),
    np.array([564,392,-477]),
    np.array([455,729,728]),
    np.array([-892,524,684]),
    np.array([-689,845,-530]),
    np.array([423,-701,434]),
    np.array([7,-33,-71]),
    np.array([630,319,-379]),
    np.array([443,580,662]),
    np.array([-789,900,-551]),
    np.array([459,-707,401])
]

b= [
    np.array([686,422,578]),
    np.array([605,423,415]),
    np.array([515,917,-361]),
    np.array([-336,658,858]),
    np.array([95,138,22]),
    np.array([-476,619,847]),
    np.array([-340,-569,-846]),
    np.array([567,-361,727]),
    np.array([-460,603,-452]),
    np.array([669,-402,600]),
    np.array([729,430,532]),
    np.array([-500,-761,534]),
    np.array([-322,571,750]),
    np.array([-466,-666,-811]),
    np.array([-429,-592,574]),
    np.array([-355,545,-477]),
    np.array([703,-491,-529]),
    np.array([-328,-685,520]),
    np.array([413,935,-424]),
    np.array([-391,539,-444]),
    np.array([586,-435,557]),
    np.array([-364,-763,-893]),
    np.array([807,-499,-711]),
    np.array([755,-354,-619]),
    np.array([553,889,-390])
]

In [73]:
def find_overlap(coords_1, coords_2):
                
    orig_dists = []
    for x in coords_1:
        dist_x = []
        for y in coords_1:
            dist = np.linalg.norm(x-y)
            dist_x.append(dist)
#             print(dist_x)
        orig_dists.append(dist_x)
#         print(orig_dists)
    
    
    common_dist = []
    for i, d in enumerate(orig_dists):
        for i2, d2, in enumerate(orig_dists):
#             if i != i2:
            common = list(set(d) & set(d2))
#             print(common)
            if len(common) > 0:
                common_dist.append(common)
    print(common_dist)
    return common_dist

In [74]:
b_rotated = all_orients(b)
test = []
for br in b_rotated:
    test.append(find_overlap(a, br))


[[0.0, 1792.8792485831275, 2436.6914043431925, 139.38794782907166, 1549.5760710594366, 145.74635501445653, 1939.0443522519024, 2329.8894823574788, 1308.5832033157083, 1951.5926829131124, 1956.4631353542034, 1317.0045558007762, 1066.2809198330428, 1070.6115075040059, 2095.407120346784, 1840.0486406614364, 1074.4924383168081, 1079.7110724633696, 1339.9085789709684, 1085.624244386611, 2367.6634051317346, 1509.0536769777277, 1510.3820708681628, 1002.1207512071587, 1136.87510307861], [0.0, 1317.0045558007762], [0.0, 2367.6634051317346], [0.0, 139.38794782907166], [0.0, 1066.2809198330428], [0.0, 1549.5760710594366], [0.0, 1510.3820708681628], [0.0, 1136.87510307861], [0.0, 2436.6914043431925], [0.0, 1085.624244386611], [0.0, 1002.1207512071587], [0.0, 1956.4631353542034], [0.0, 1509.0536769777277], [1792.8792485831275, 0.0], [0.0, 145.74635501445653], [0.0, 1079.7110724633696], [0.0, 2095.407120346784], [0.0, 2329.8894823574788], [0.0, 1840.0486406614364], [0.0, 1339.9085789709684], [0.0, 1

In [20]:
common = []
for i, d in enumerate(orig_dists):
    for i2, d2, in enumerate(orig_dists):
        if i != i2:
            c = list(set(d) & set(d2))
            if len(c) > 0:
                common.append(c)
            

In [49]:
b_rotated

[[array([686, 422, 578]),
  array([ 578,  422, -686]),
  array([-686,  422, -578]),
  array([-578,  422,  686]),
  array([-422,  686,  578]),
  array([ 422, -686,  578]),
  array([ 686, -578,  422]),
  array([ 422, -578, -686]),
  array([-686, -578, -422]),
  array([-422, -578,  686]),
  array([578, 686, 422]),
  array([-578, -686,  422]),
  array([ 686, -422, -578]),
  array([-578, -422, -686]),
  array([-686, -422,  578]),
  array([ 578, -422,  686]),
  array([ 422,  686, -578]),
  array([-422, -686, -578]),
  array([ 686,  578, -422]),
  array([-422,  578, -686]),
  array([-686,  578,  422]),
  array([422, 578, 686]),
  array([-578,  686, -422]),
  array([ 578, -686, -422])],
 [array([605, 423, 415]),
  array([ 415,  423, -605]),
  array([-605,  423, -415]),
  array([-415,  423,  605]),
  array([-423,  605,  415]),
  array([ 423, -605,  415]),
  array([ 605, -415,  423]),
  array([ 423, -415, -605]),
  array([-605, -415, -423]),
  array([-423, -415,  605]),
  array([415, 605, 423]),